export { default as AperturaAngelicaHeader } from './AperturaAngelicaHeader';
export { default as SonoterapiaHeader } from './SonoterapiaHeader';
export { default as TerapiasHeader } from './TerapiasHeader';
export { default as AcademiaHeader } from './AcademiaHeader';
export { default as TiendaHeader } from './TiendaHeader';
export { default as BlogHeader } from './BlogHeader';
export { default as MensajeHeader } from './MensajeHeader';
export { default as EventosHeader } from './EventosHeader';
export { default as ReservasHeader } from './ReservasHeader';