import React, { createContext, useState, useContext } from 'react';

// Crear el contexto
const LanguageContext = createContext();

// Idiomas disponibles
export const AVAILABLE_LANGUAGES = ['Español', 'English', 'Deutsch', 'Italiano', 'Français'];

// Traducciones globales
export const TRANSLATIONS = {
  'Español': {
    title: "PLATAFORMA ANGÉLICA",
    blessing: "Dios nos bendice mil veces mil",
    subtitle: "Conecta con tus ángeles.",
    subtitle2: "Transforma tu vida.",
    login: "🔒 Iniciar Sesión",
    register: "👤 Registrarse",
    language: "Idioma",
    followUs: "Síguenos:",
    messageCount: "Mensaje",
    of: "de",
    loginPage: {
      title: "Iniciar Sesión",
      subtitle: "Bienvenido de nuevo a la Plataforma Angélica",
      email: "Correo Electrónico",
      password: "Contraseña",
      loginButton: "Iniciar Sesión",
      loading: "Cargando...",
      noAccount: "¿No tienes una cuenta?",
      registerHere: "Regístrate aquí",
      forgotPassword: "¿Olvidaste tu contraseña?",
      back: "Volver",
      invalidCredentials: "Credenciales inválidas. Inténtalo de nuevo."
    },
    registerPage: {
      title: "Crear Cuenta",
      subtitle: "Únete a nuestra comunidad espiritual",
      firstName: "Nombre",
      lastName: "Apellidos",
      email: "Correo Electrónico",
      password: "Contraseña",
      confirmPassword: "Confirmar Contraseña",
      preferredLanguage: "Idioma Preferente",
      phone: "Teléfono",
      address: "Dirección",
      city: "Ciudad",
      state: "Estado / Provincia",
      postalCode: "Código Postal",
      selectCountry: "Selecciona un país",
      preferredContact: "Medio de contacto preferido",
      acceptTerms: "Acepto los",
      termsAndConditions: "Términos y Condiciones",
      and: "y la",
      privacyPolicy: "Política de Privacidad",
      registerButton: "Registrarse",
      registering: "Registrando...",
      alreadyHaveAccount: "¿Ya tienes cuenta?",
      loginHere: "Inicia sesión aquí",
      back: "Volver",
      passwordMismatch: "Las contraseñas no coinciden",
      success: "Registro exitoso. Revisa tu correo para confirmar la cuenta.",
      ageError: "Debe ser mayor de 18 años para registrarse",
      personalInfo: "Información Personal",
      security: "Seguridad", 
      preferences: "Preferencias y Contacto",
      location: "Ubicación",
      errorTitle: "Error en el Registro",
      understood: "Entendido",
      successTitle: "¡Registro Exitoso!",
      goToLogin: "Ir al Login",
      ageErrorTitle: "Registro No Permitido",
      ageErrorMessage: "Lo sentimos, el registro está restringido a personas mayores de 18 años."
    },
    footer: {
      terms: "Términos de Uso",
      privacy: "Política de Privacidad",
      contact: "Contacto",
      rightsReserved: "Todos los derechos reservados"
    },
    termsPage: {
      title: "Términos de Uso",
      description: "Bienvenido a la Plataforma Angélica. Al acceder y utilizar nuestro sitio web, aceptas cumplir con los siguientes términos y condiciones:",
      point1: "El contenido ofrecido es con fines espirituales y de bienestar.",
      point2: "No sustituye tratamientos médicos ni terapéuticos profesionales.",
      point3: "El uso indebido del contenido puede conllevar a la suspensión de la cuenta.",
      point4: "Respetamos la privacidad de tus datos según nuestra política.",
      point5: "Nos reservamos el derecho a modificar estos términos en cualquier momento.",
      contentTitle: "Contenido Espiritual",
      useTitle: "Uso Responsable",
      policiesTitle: "Políticas de Uso",
      privacyTitle: "Privacidad",
      modificationsTitle: "Modificaciones",
      acceptance: "Aceptación de Términos",
      acceptanceText: "Al utilizar nuestra plataforma, confirmas que has leído, entendido y aceptado estos términos de uso.",
      back: "Volver",
      close: "✖"
    },
    privacyPage: {
      title: "Política de Privacidad",
      description: "En Plataforma Angélica valoramos profundamente tu privacidad y nos comprometemos a proteger tu información personal. Esta política explica cómo recopilamos, usamos y protegemos tus datos:",
      point1: "Los datos que proporcionas (nombre, email, preferencias) se usan únicamente para brindarte una experiencia espiritual personalizada.",
      point2: "No compartimos tus datos con terceros sin tu consentimiento expreso.",
      point3: "Utilizamos Supabase como backend seguro para el almacenamiento y autenticación de usuarios.",
      point4: "Puedes solicitar en cualquier momento la eliminación o modificación de tu información.",
      point5: "Esta política puede actualizarse para adaptarse a nuevas normativas o mejoras del servicio.",
      dataTitle: "Uso de Datos Personales",
      protectionTitle: "Protección de Información",
      infrastructureTitle: "Infraestructura Segura",
      rightsTitle: "Derechos del Usuario",
      updatesTitle: "Actualizaciones",
      commitment: "Nuestro Compromiso",
      commitmentText: "Tu privacidad es fundamental para nosotros. Nos comprometemos a mantener la confidencialidad y seguridad de tu información personal en todo momento.",
      back: "Volver",
      close: "✖"
    },
    contactPage: {
      title: "Contacto",
      description: "Puedes escribirnos a través de los siguientes medios:",
      email: "Email: contacto@plataformaangelica.com",
      whatsapp: "WhatsApp: +123 456 789",
      instagram: "Instagram: @plataforma_angelica",
      facebook: "Facebook: Plataforma Angélica Oficial",
      thanks: "Gracias por comunicarte con nosotros 🌟",
      responseMessage: "Te responderemos lo antes posible para ayudarte en tu camino espiritual 🌟",
    },
    loadingMessages: [
      "Preparando tu espacio sagrado...",
      "Conectando con la energía angelical...",
      "Abriendo los canales de luz divina...",
      "Invocando la protección celestial...",
      "Activando tu conexión espiritual...",
      "Los ángeles te están esperando...",
      "Creando un ambiente de paz y amor...",
      "Sintonizando con las frecuencias angelicales...",
      "Preparando tu encuentro divino...",
      "¡Bienvenido a tu transformación!"
    ],
    dashboard: {
      welcome: "Dashboard Personal",
      home: "Inicio",
      angelicReading: "Apertura Angelica",
      soundTherapy: "Sonoterapia y Canalizaciones",
      therapies: "Terapias y Limpiezas",
      academy: "Academia Angelica",
      dailyMessage: "Mensaje Diario",
      blogPodcast: "Blog & Podcast",
      store: "Tienda Angelica",
      level: "Nivel",
      points: "Puntos de Luz",
      consecutiveDays: "Días Consecutivos",
      completedSessions: "Sesiones",
      channelingsListened: "Canalizaciones",
      coursesFinished: "Cursos",
      dailyMessageSection: "MENSAJE DEL DÍA",
      seeAngelicMessages: "VER MENSAJES ANGELICALES",
      eventsTitle: "Próximos Eventos del Angelólogo",
      eventDate: "Fecha",
      eventTime: "Hora",
      eventDuration: "Duración",
      eventModality: "Modalidad",
      eventLocation: "Ubicación",
      eventPrice: "Precio",
      eventSpaces: "Cupos",
      eventRegistered: "Inscritos",
      viewDetails: "Ver Detalles",
      subscribed: "Inscrito",
      subscribe: "Inscribirse",
      cart: "Carrito de Compra",
      emptyCart: "Tu carrito está vacío",
      addProducts: "Agrega productos desde cualquier sección de la plataforma",
      total: "Total",
      clearCart: "Vaciar Carrito",
      proceedPayment: "Proceder al Pago",
      settings: "Configuración de Usuario",
      personalInfo: "Información Personal",
      name: "Nombre",
      lastName: "Apellido",
      email: "Correo Electrónico",
      phone: "Teléfono",
      birthDate: "Fecha de Nacimiento",
      country: "País",
      platformPrefs: "Preferencias de la Plataforma",
      language: "Idioma",
      notifications: "Recibir notificaciones",
      emailMarketing: "Emails promocionales",
      darkMode: "Modo oscuro",
      saveChanges: "Guardar Cambios",
      logout: "Cerrar Sesión",
      events: {
        previous: "Anterior",
        next: "Siguiente"
      }
    },
    calendar: {
      weekDays: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa']
    }
  },
  'English': {
    title: "ANGELIC PLATFORM",
    blessing: "God blesses us a thousand times a thousand",
    subtitle: "Connect with your angels.",
    subtitle2: "Transform your life.",
    login: "🔒 Login",
    register: "👤 Register",
    language: "Language",
    followUs: "Follow us:",
    messageCount: "Message",
    of: "of",
    loginPage: {
      title: "Login",
      subtitle: "Welcome back to the Angelic Platform",
      email: "Email",
      password: "Password",
      loginButton: "Login",
      loading: "Loading...",
      noAccount: "Don't have an account?",
      registerHere: "Register here",
      forgotPassword: "Forgot your password?",
      back: "Back",
      invalidCredentials: "Invalid credentials. Please try again."
    },
    registerPage: {
      title: "Create Account",
      subtitle: "Join our spiritual community",
      firstName: "First Name",
      lastName: "Last Name", 
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      preferredLanguage: "Preferred Language",
      phone: "Phone",
      address: "Address",
      city: "City",
      state: "State / Province",
      postalCode: "Postal Code",
      selectCountry: "Select a country",
      preferredContact: "Preferred contact method",
      acceptTerms: "I accept the",
      termsAndConditions: "Terms and Conditions",
      and: "and the",
      privacyPolicy: "Privacy Policy",
      registerButton: "Register",
      registering: "Registering...",
      alreadyHaveAccount: "Already have an account?",
      loginHere: "Login here",
      back: "Back",
      passwordMismatch: "Passwords do not match",
      success: "Registration successful. Check your email to confirm your account.",
      ageError: "You must be 18 years or older to register",
      personalInfo: "Personal Information",
      security: "Security",
      preferences: "Preferences and Contact",
      location: "Location",
      errorTitle: "Registration Error",
      understood: "Understood",
      successTitle: "Registration Successful!",
      goToLogin: "Go to Login",
      ageErrorTitle: "Registration Not Allowed",
      ageErrorMessage: "Sorry, registration is restricted to people over 18 years old."
    },
    footer: {
      terms: "Terms of Use",
      privacy: "Privacy Policy",
      contact: "Contact",
      rightsReserved: "All rights reserved"
    },
    termsPage: {
      title: "Terms of Use",
      description: "Welcome to the Angelic Platform. By accessing and using our website, you agree to comply with the following terms and conditions:",
      point1: "The content offered is for spiritual and wellness purposes.",
      point2: "It does not replace professional medical or therapeutic treatments.",
      point3: "Misuse of content may result in account suspension.",
      point4: "We respect the privacy of your data according to our policy.",
      point5: "We reserve the right to modify these terms at any time.",
      contentTitle: "Spiritual Content",
      useTitle: "Responsible Use",
      policiesTitle: "Usage Policies",
      privacyTitle: "Privacy",
      modificationsTitle: "Modifications",
      acceptance: "Terms Acceptance",
      acceptanceText: "By using our platform, you confirm that you have read, understood, and accepted these terms of use.",
      back: "Back",
      close: "✖"
    },
    privacyPage: {
      title: "Privacy Policy",
      description: "At Angelic Platform, we deeply value your privacy and are committed to protecting your personal information. This policy explains how we collect, use, and protect your data:",
      point1: "The data you provide (name, email, preferences) is used solely to provide you with a personalized spiritual experience.",
      point2: "We do not share your data with third parties without your express consent.",
      point3: "We use Supabase as a secure backend for user storage and authentication.",
      point4: "You can request the deletion or modification of your information at any time.",
      point5: "This policy may be updated to adapt to new regulations or service improvements.",
      dataTitle: "Personal Data Usage",
      protectionTitle: "Information Protection",
      infrastructureTitle: "Secure Infrastructure",
      rightsTitle: "User Rights",
      updatesTitle: "Updates",
      commitment: "Our Commitment",
      commitmentText: "Your privacy is fundamental to us. We are committed to maintaining the confidentiality and security of your personal information at all times.",
      back: "Back",
      close: "✖"
    },
    contactPage: {
      title: "Contact",
      description: "You can contact us through the following means:",
      email: "Email: contact@angelicplatform.com",
      whatsapp: "WhatsApp: +123 456 789",
      instagram: "Instagram: @angelic_platform",
      facebook: "Facebook: Official Angelic Platform",
      thanks: "Thank you for contacting us 🌟",
      responseMessage: "We will respond as soon as possible to help you on your spiritual journey 🌟",
      back: "Back",
      close: "✖"
    },
    loadingMessages: [
      "Preparing your sacred space...",
      "Connecting with angelic energy...",
      "Opening the channels of divine light...",
      "Invoking celestial protection...",
      "Activating your spiritual connection...",
      "The angels are waiting for you...",
      "Creating an environment of peace and love...",
      "Tuning into angelic frequencies...",
      "Preparing your divine encounter...",
      "Welcome to your transformation!"
    ],
    dashboard: {
      welcome: "Personal Dashboard",
      home: "Home",
      angelicReading: "Angelic Opening",
      soundTherapy: "Sound Therapy and Channeling",
      therapies: "Therapies and Cleansing",
      academy: "Angelic Academy",
      dailyMessage: "Daily Message",
      blogPodcast: "Blog & Podcast",
      store: "Angelic Store",
      level: "Level",
      points: "Light Points",
      consecutiveDays: "Consecutive Days",
      completedSessions: "Sessions",
      channelingsListened: "Channeling",
      coursesFinished: "Courses",
      dailyMessageSection: "DAILY MESSAGE",
      seeAngelicMessages: "SEE ANGELIC MESSAGES",
      eventsTitle: "Upcoming Angelologist Events",
      eventDate: "Date",
      eventTime: "Time",
      eventDuration: "Duration",
      eventModality: "Modality",
      eventLocation: "Location",
      eventPrice: "Price",
      eventSpaces: "Spaces",
      eventRegistered: "Registered",
      viewDetails: "View Details",
      subscribed: "Subscribed",
      subscribe: "Subscribe",
      cart: "Shopping Cart",
      emptyCart: "Your cart is empty",
      addProducts: "Add products from any platform section",
      total: "Total",
      clearCart: "Clear Cart",
      proceedPayment: "Proceed to Payment",
      settings: "User Settings",
      personalInfo: "Personal Information",
      name: "Name",
      lastName: "Last Name",
      email: "Email",
      phone: "Phone",
      birthDate: "Birth Date",
      country: "Country",
      platformPrefs: "Platform Preferences",
      language: "Language",
      notifications: "Receive notifications",
      emailMarketing: "Promotional emails",
      darkMode: "Dark mode",
      saveChanges: "Save Changes",
      logout: "Logout",
      events: {
        previous: "Previous",
        next: "Next"
      }
    },
    calendar: {
      weekDays: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
    }
  },
  'Français': {
    title: "PLATEFORME ANGÉLIQUE",
    blessing: "Dieu nous bénit mille fois mille",
    subtitle: "Connectez-vous avec vos anges.",
    subtitle2: "Transformez votre vie.",
    login: "🔒 Se connecter",
    register: "👤 S'inscrire",
    language: "Langue",
    followUs: "Suivez-nous:",
    messageCount: "Message",
    of: "de",
    loginPage: {
      title: "Se connecter",
      subtitle: "Bienvenue sur la Plateforme Angélique",
      email: "Email",
      password: "Mot de passe",
      loginButton: "Se connecter",
      loading: "Chargement...",
      noAccount: "Vous n'avez pas de compte?",
      registerHere: "Inscrivez-vous ici",
      forgotPassword: "Mot de passe oublié?",
      back: "Retour",
      invalidCredentials: "Identifiants invalides. Veuillez réessayer."
    },
    registerPage: {
      title: "Créer un compte",
      subtitle: "Rejoignez notre communauté spirituelle",
      firstName: "Prénom",
      lastName: "Nom de famille",
      email: "Email",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      preferredLanguage: "Langue préférée",
      phone: "Téléphone",
      address: "Adresse",
      city: "Ville",
      state: "État / Province",
      postalCode: "Code postal",
      selectCountry: "Sélectionnez un pays",
      preferredContact: "Mode de contact préféré",
      acceptTerms: "J'accepte les",
      termsAndConditions: "Conditions d'utilisation",
      and: "et la",
      privacyPolicy: "Politique de confidentialité",
      registerButton: "S'inscrire",
      registering: "Inscription...",
      alreadyHaveAccount: "Vous avez déjà un compte?",
      loginHere: "Connectez-vous ici",
      back: "Retour",
      passwordMismatch: "Les mots de passe ne correspondent pas",
      success: "Inscription réussie. Vérifiez votre email pour confirmer votre compte.",
      ageError: "Vous devez avoir 18 ans ou plus pour vous inscrire",
      personalInfo: "Informations Personnelles",
      security: "Sécurité",
      preferences: "Préférences et Contact",
      location: "Localisation",
      errorTitle: "Erreur d'Inscription",
      understood: "Compris",
      successTitle: "Inscription Réussie!",
      goToLogin: "Aller à la Connexion",
      ageErrorTitle: "Inscription Non Autorisée",
      ageErrorMessage: "Désolé, l'inscription est réservée aux personnes de plus de 18 ans."
    },
    footer: {
      terms: "Conditions d'utilisation",
      privacy: "Politique de confidentialité",
      contact: "Contact",
      rightsReserved: "Tous droits réservés"
    },
    termsPage: {
      title: "Conditions d'utilisation",
      description: "Bienvenue sur la Plateforme Angélique. En accédant et en utilisant notre site Web, vous acceptez de respecter les termes et conditions suivants:",
      point1: "Le contenu proposé est à des fins spirituelles et de bien-être.",
      point2: "Il ne remplace pas les traitements médicaux ou thérapeutiques professionnels.",
      point3: "L'utilisation abusive du contenu peut entraîner la suspension du compte.",
      point4: "Nous respectons la confidentialité de vos données selon notre politique.",
      point5: "Nous nous réservons le droit de modifier ces conditions à tout moment.",
      contentTitle: "Contenu Spirituel",
      useTitle: "Utilisation Responsable",
      policiesTitle: "Politiques d'Utilisation",
      privacyTitle: "Confidentialité",
      modificationsTitle: "Modifications",
      acceptance: "Acceptation des Conditions",
      acceptanceText: "En utilisant notre plateforme, vous confirmez que vous avez lu, compris et accepté ces conditions d'utilisation.",
      back: "Retour",
      close: "✖"
    },
    privacyPage: {
      title: "Politique de confidentialité",
      description: "À la Plateforme Angélique, nous valorisons profondément votre confidentialité et nous nous engageons à protéger vos informations personnelles. Cette politique explique comment nous collectons, utilisons et protégeons vos données:",
      point1: "Les données que vous fournissez (nom, email, préférences) sont utilisées uniquement pour vous offrir une expérience spirituelle personnalisée.",
      point2: "Nous ne partageons pas vos données avec des tiers sans votre consentement exprès.",
      point3: "Nous utilisons Supabase comme backend sécurisé pour le stockage et l'authentification des utilisateurs.",
      point4: "Vous pouvez demander la suppression ou la modification de vos informations à tout moment.",
      point5: "Cette politique peut être mise à jour pour s'adapter aux nouvelles réglementations ou améliorations du service.",
      dataTitle: "Utilisation des Données Personnelles",
      protectionTitle: "Protection des Informations",
      infrastructureTitle: "Infrastructure Sécurisée",
      rightsTitle: "Droits de l'Utilisateur",
      updatesTitle: "Mises à jour",
      commitment: "Notre Engagement",
      commitmentText: "Votre confidentialité est fondamentale pour nous. Nous nous engageons à maintenir la confidentialité et la sécurité de vos informations personnelles en tout temps.",
      back: "Retour",
      close: "✖"
    },
    contactPage: {
      title: "Contact",
      description: "Vous pouvez nous contacter par les moyens suivants:",
      email: "Email: contact@plateformeaangelique.fr",
      whatsapp: "WhatsApp: +123 456 789",
      instagram: "Instagram: @plateforme_angelique",
      facebook: "Facebook: Plateforme Angélique Officielle",
      thanks: "Merci de nous avoir contactés 🌟",
      responseMessage: "Nous vous répondrons dès que possible pour vous aider dans votre cheminement spirituel 🌟",
      back: "Retour",
      close: "✖"
    },
    loadingMessages: [
      "Préparation de votre espace sacré...",
      "Connexion avec l'énergie angélique...",
      "Ouverture des canaux de lumière divine...",
      "Invocation de la protection céleste...",
      "Activation de votre connexion spirituelle...",
      "Les anges vous attendent...",
      "Création d'un environnement de paix et d'amour...",
      "Syntonisation avec les fréquences angéliques...",
      "Préparation de votre rencontre divine...",
      "Bienvenue dans votre transformation!"
    ],
    dashboard: {
      welcome: "Tableau de bord personnel",
      home: "Accueil",
      angelicReading: "Ouverture Angélique",
      soundTherapy: "Sonothérapie et Canalisations",
      therapies: "Thérapies et Nettoyages",
      academy: "Académie Angélique",
      dailyMessage: "Message Quotidien",
      blogPodcast: "Blog & Podcast",
      store: "Boutique Angélique",
      level: "Niveau",
      points: "Points de Lumière",
      consecutiveDays: "Jours Consécutifs",
      completedSessions: "Sessions",
      channelingsListened: "Canalisations",
      coursesFinished: "Cours",
      dailyMessageSection: "MESSAGE DU JOUR",
      seeAngelicMessages: "VOIR LES MESSAGES ANGÉLIQUES",
      eventsTitle: "Événements à Venir de l'Angéologue",
      eventDate: "Date",
      eventTime: "Heure",
      eventDuration: "Durée",
      eventModality: "Modalité",
      eventLocation: "Lieu",
      eventPrice: "Prix",
      eventSpaces: "Places",
      eventRegistered: "Inscrits",
      viewDetails: "Voir Détails",
      subscribed: "Inscrit",
      subscribe: "S'inscrire",
      cart: "Panier d'Achat",
      emptyCart: "Votre panier est vide",
      addProducts: "Ajoutez des produits depuis n'importe quelle section",
      total: "Total",
      clearCart: "Vider le Panier",
      proceedPayment: "Procéder au Paiement",
      settings: "Paramètres Utilisateur",
      personalInfo: "Informations Personnelles",
      name: "Nom",
      lastName: "Prénom",
      email: "Email",
      phone: "Téléphone",
      birthDate: "Date de Naissance",
      country: "Pays",
      platformPrefs: "Préférences de la Plateforme",
      language: "Langue",
      notifications: "Recevoir les notifications",
      emailMarketing: "Emails promotionnels",
      darkMode: "Mode sombre",
      saveChanges: "Sauvegarder les Modifications",
      logout: "Se Déconnecter",
      events: {
        previous: "Précédent",
        next: "Suivant"
      }
    },
    calendar: {
      weekDays: ['Di', 'Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa']
    }
  },
  'Deutsch': {
    title: "ENGELHAFTE PLATTFORM",
    blessing: "Gott segnet uns tausendmal tausend",
    subtitle: "Verbinden Sie sich mit Ihren Engeln.",
    subtitle2: "Verwandeln Sie Ihr Leben.",
    login: "🔒 Anmelden",
    register: "👤 Registrieren",
    language: "Sprache",
    followUs: "Folgen Sie uns:",
    messageCount: "Nachricht",
    of: "von",
    loginPage: {
      title: "Anmelden",
      subtitle: "Willkommen zurück zur Engelplattform",
      email: "E-Mail",
      password: "Passwort",
      loginButton: "Anmelden",
      loading: "Laden...",
      noAccount: "Haben Sie kein Konto?",
      registerHere: "Hier registrieren",
      forgotPassword: "Passwort vergessen?",
      back: "Zurück",
      invalidCredentials: "Ungültige Anmeldedaten. Bitte versuchen Sie es erneut."
    },
    registerPage: {
      title: "Konto erstellen",
      subtitle: "Treten Sie unserer spirituellen Gemeinschaft bei",
      firstName: "Vorname",
      lastName: "Nachname",
      email: "E-Mail",
      password: "Passwort",
      confirmPassword: "Passwort bestätigen",
      preferredLanguage: "Bevorzugte Sprache",
      phone: "Telefon",
      address: "Adresse",
      city: "Stadt",
      state: "Staat / Provinz",
      postalCode: "Postleitzahl",
      selectCountry: "Land auswählen",
      preferredContact: "Bevorzugte Kontaktmethode",
      acceptTerms: "Ich akzeptiere die",
      termsAndConditions: "Nutzungsbedingungen",
      and: "und die",
      privacyPolicy: "Datenschutzrichtlinie",
      registerButton: "Registrieren",
      registering: "Registrierung...",
      alreadyHaveAccount: "Haben Sie bereits ein Konto?",
      loginHere: "Hier anmelden",
      back: "Zurück",
      passwordMismatch: "Passwörter stimmen nicht überein",
      success: "Registrierung erfolgreich. Überprüfen Sie Ihre E-Mail, um Ihr Konto zu bestätigen.",
      ageError: "Sie müssen 18 Jahre oder älter sein, um sich zu registrieren",
      personalInfo: "Persönliche Informationen",
      security: "Sicherheit",
      preferences: "Präferenzen und Kontakt",
      location: "Standort",
      errorTitle: "Registrierungsfehler",
      understood: "Verstanden",
      successTitle: "Registrierung Erfolgreich!",
      goToLogin: "Zur Anmeldung",
      ageErrorTitle: "Registrierung Nicht Erlaubt",
      ageErrorMessage: "Entschuldigung, die Registrierung ist auf Personen über 18 Jahre beschränkt."
    },
    footer: {
      terms: "Nutzungsbedingungen",
      privacy: "Datenschutzrichtlinie",
      contact: "Kontakt",
      rightsReserved: "Alle Rechte vorbehalten"
    },
    termsPage: {
      title: "Nutzungsbedingungen",
      description: "Willkommen bei der Engelplattform. Durch den Zugriff auf und die Nutzung unserer Website stimmen Sie zu, die folgenden Geschäftsbedingungen einzuhalten:",
      point1: "Die angebotenen Inhalte dienen spirituellen und Wellness-Zwecken.",
      point2: "Sie ersetzen keine professionellen medizinischen oder therapeutischen Behandlungen.",
      point3: "Missbrauch von Inhalten kann zur Kontosperrung führen.",
      point4: "Wir respektieren die Privatsphäre Ihrer Daten gemäß unserer Richtlinie.",
      point5: "Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu ändern.",
      contentTitle: "Spiritueller Inhalt",
      useTitle: "Verantwortungsvolle Nutzung",
      policiesTitle: "Nutzungsrichtlinien",
      privacyTitle: "Datenschutz",
      modificationsTitle: "Änderungen",
      acceptance: "Akzeptanz der Bedingungen",
      acceptanceText: "Durch die Nutzung unserer Plattform bestätigen Sie, dass Sie diese Nutzungsbedingungen gelesen, verstanden und akzeptiert haben.",
      back: "Zurück",
      close: "✖"
    },
    privacyPage: {
      title: "Datenschutzrichtlinie",
      description: "Bei der Engelplattform schätzen wir Ihre Privatsphäre sehr und verpflichten uns, Ihre persönlichen Daten zu schützen. Diese Richtlinie erklärt, wie wir Ihre Daten sammeln, verwenden und schützen:",
      point1: "Die von Ihnen bereitgestellten Daten (Name, E-Mail, Präferenzen) werden ausschließlich verwendet, um Ihnen eine personalisierte spirituelle Erfahrung zu bieten.",
      point2: "Wir teilen Ihre Daten nicht mit Dritten ohne Ihre ausdrückliche Zustimmung.",
      point3: "Wir verwenden Supabase als sicheres Backend für die Speicherung und Authentifizierung von Benutzern.",
      point4: "Sie können jederzeit die Löschung oder Änderung Ihrer Informationen beantragen.",
      point5: "Diese Richtlinie kann aktualisiert werden, um sich an neue Vorschriften oder Serviceverbesserungen anzupassen.",
      dataTitle: "Nutzung Persönlicher Daten",
      protectionTitle: "Informationsschutz",
      infrastructureTitle: "Sichere Infrastruktur",
      rightsTitle: "Benutzerrechte",
      updatesTitle: "Aktualisierungen",
      commitment: "Unser Engagement",
      commitmentText: "Ihre Privatsphäre ist für uns von grundlegender Bedeutung. Wir verpflichten uns, die Vertraulichkeit und Sicherheit Ihrer persönlichen Daten jederzeit zu gewährleisten.",
      back: "Zurück",
      close: "✖"
    },
    contactPage: {
      title: "Kontakt",
      description: "Sie können uns über folgende Wege erreichen:",
      email: "E-Mail: kontakt@engelplattform.de",
      whatsapp: "WhatsApp: +123 456 789",
      instagram: "Instagram: @engel_plattform",
      facebook: "Facebook: Offizielle Engelplattform",
      thanks: "Vielen Dank, dass Sie uns kontaktiert haben 🌟",
      responseMessage: "Wir werden Ihnen so schnell wie möglich antworten, um Ihnen auf Ihrem spirituellen Weg zu helfen 🌟",
      back: "Zurück",
      close: "✖"
    },
    loadingMessages: [
      "Vorbereitung Ihres heiligen Raumes...",
      "Verbindung mit der Engelsenergie...",
      "Öffnung der Kanäle des göttlichen Lichts...",
      "Anrufung des himmlischen Schutzes...",
      "Aktivierung Ihrer spirituellen Verbindung...",
      "Die Engel warten auf Sie...",
      "Schaffung einer Atmosphäre von Frieden und Liebe...",
      "Einstimmung auf Engelsfrequenzen...",
      "Vorbereitung Ihrer göttlichen Begegnung...",
      "Willkommen zu Ihrer Transformation!"
    ],
    dashboard: {
      welcome: "Persönliches Dashboard",
      home: "Startseite",
      angelicReading: "Engelische Öffnung",
      soundTherapy: "Klangtherapie und Kanalisierungen",
      therapies: "Therapien und Reinigungen",
      academy: "Engelakademie",
      dailyMessage: "Tägliche Botschaft",
      blogPodcast: "Blog & Podcast",
      store: "Engel-Shop",
      level: "Level",
      points: "Lichtpunkte",
      consecutiveDays: "Aufeinanderfolgende Tage",
      completedSessions: "Sitzungen",
      channelingsListened: "Kanalisierungen",
      coursesFinished: "Kurse",
      dailyMessageSection: "TÄGLICHE BOTSCHAFT",
      seeAngelicMessages: "ENGELBOTSCHAFTEN ANSEHEN",
      eventsTitle: "Bevorstehende Veranstaltungen des Angelologen",
      eventDate: "Datum",
      eventTime: "Uhrzeit",
      eventDuration: "Dauer",
      eventModality: "Modalität",
      eventLocation: "Ort",
      eventPrice: "Preis",
      eventSpaces: "Plätze",
      eventRegistered: "Angemeldet",
      viewDetails: "Details ansehen",
      subscribed: "Angemeldet",
      subscribe: "Anmelden",
      cart: "Warenkorb",
      emptyCart: "Ihr Warenkorb ist leer",
      addProducts: "Fügen Sie Produkte aus jedem Bereich der Plattform hinzu",
      total: "Gesamt",
      clearCart: "Warenkorb leeren",
      proceedPayment: "Zur Zahlung fortfahren",
      settings: "Benutzereinstellungen",
      personalInfo: "Persönliche Informationen",
      name: "Name",
      lastName: "Nachname",
      email: "E-Mail",
      phone: "Telefon",
      birthDate: "Geburtsdatum",
      country: "Land",
      platformPrefs: "Plattform-Einstellungen",
      language: "Sprache",
      notifications: "Benachrichtigungen erhalten",
      emailMarketing: "Werbe-E-Mails",
      darkMode: "Dunkelmodus",
      saveChanges: "Änderungen speichern",
      logout: "Abmelden",
      events: {
        previous: "Zurück",
        next: "Weiter"
      }
    },
    calendar: {
      weekDays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa']
    }
  },
  'Italiano': {
    title: "PIATTAFORMA ANGELICA",
    blessing: "Dio ci benedice mille volte mille",
    subtitle: "Connettiti con i tuoi angeli.",
    subtitle2: "Trasforma la tua vita.",
    login: "🔒 Accedi",
    register: "👤 Registrati",
    language: "Lingua",
    followUs: "Seguici:",
    messageCount: "Messaggio",
    of: "di",
    loginPage: {
      title: "Accedi",
      subtitle: "Bentornato alla Piattaforma Angelica",
      email: "Email",
      password: "Password",
      loginButton: "Accedi",
      loading: "Caricamento...",
      noAccount: "Non hai un account?",
      registerHere: "Registrati qui",
      forgotPassword: "Hai dimenticato la password?",
      back: "Indietro",
      invalidCredentials: "Credenziali non valide. Riprova."
    },
    registerPage: {
      title: "Crea account",
      subtitle: "Unisciti alla nostra comunità spirituale",
      firstName: "Nome",
      lastName: "Cognome",
      email: "Email",
      password: "Password",
      confirmPassword: "Conferma password",
      preferredLanguage: "Lingua preferita",
      phone: "Telefono",
      address: "Indirizzo",
      city: "Città",
      state: "Stato / Provincia",
      postalCode: "Codice postale",
      selectCountry: "Seleziona un paese",
      preferredContact: "Metodo di contatto preferito",
      acceptTerms: "Accetto i",
      termsAndConditions: "Termini e condizioni",
      and: "e la",
      privacyPolicy: "Politica sulla privacy",
      registerButton: "Registrati",
      registering: "Registrazione...",
      alreadyHaveAccount: "Hai già un account?",
      loginHere: "Accedi qui",
      back: "Indietro",
      passwordMismatch: "Le password non corrispondono",
      success: "Registrazione completata. Controlla la tua email per confermare l'account.",
      ageError: "Devi avere 18 anni o più per registrarti",
      personalInfo: "Informazioni Personali",
      security: "Sicurezza",
      preferences: "Preferenze e Contatto",
      location: "Posizione",
      errorTitle: "Errore di Registrazione",
      understood: "Capito",
      successTitle: "Registrazione Riuscita!",
      goToLogin: "Vai al Login",
      ageErrorTitle: "Registrazione Non Consentita",
      ageErrorMessage: "Siamo spiacenti, la registrazione è riservata alle persone di età superiore ai 18 anni."
    },
    footer: {
      terms: "Termini di utilizzo",
      privacy: "Politica sulla privacy",
      contact: "Contatto",
      rightsReserved: "Tutti i diritti riservati"
    },
    termsPage: {
      title: "Termini di utilizzo",
      description: "Benvenuto alla Piattaforma Angelica. Accedendo e utilizzando il nostro sito web, accetti di rispettare i seguenti termini e condizioni:",
      point1: "Il contenuto offerto è a scopi spirituali e di benessere.",
      point2: "Non sostituisce trattamenti medici o terapeutici professionali.",
      point3: "L'uso improprio del contenuto può portare alla sospensione dell'account.",
      point4: "Rispettiamo la privacy dei tuoi dati secondo la nostra politica.",
      point5: "Ci riserviamo il diritto di modificare questi termini in qualsiasi momento.",
      contentTitle: "Contenuto Spirituale",
      useTitle: "Uso Responsabile",
      policiesTitle: "Politiche di Utilizzo",
      privacyTitle: "Privacy",
      modificationsTitle: "Modifiche",
      acceptance: "Accettazione dei Termini",
      acceptanceText: "Utilizzando la nostra piattaforma, confermi di aver letto, compreso e accettato questi termini di utilizzo.",
      back: "Indietro",
      close: "✖"
    },
    privacyPage: {
      title: "Politica sulla privacy",
      description: "Alla Piattaforma Angelica, valutiamo profondamente la tua privacy e ci impegniamo a proteggere le tue informazioni personali. Questa politica spiega come raccogliamo, utilizziamo e proteggiamo i tuoi dati:",
      point1: "I dati che fornisci (nome, email, preferenze) vengono utilizzati esclusivamente per offrirti un'esperienza spirituale personalizzata.",
      point2: "Non condividiamo i tuoi dati con terze parti senza il tuo consenso espresso.",
      point3: "Utilizziamo Supabase come backend sicuro per l'archiviazione e l'autenticazione degli utenti.",
      point4: "Puoi richiedere in qualsiasi momento la cancellazione o modifica delle tue informazioni.",
      point5: "Questa politica può essere aggiornata per adattarsi a nuove normative o miglioramenti del servizio.",
      dataTitle: "Utilizzo dei Dati Personali",
      protectionTitle: "Protezione delle Informazioni",
      infrastructureTitle: "Infrastruttura Sicura",
      rightsTitle: "Diritti dell'Utente",
      updatesTitle: "Aggiornamenti",
      commitment: "Il Nostro Impegno",
      commitmentText: "La tua privacy è fondamentale per noi. Ci impegniamo a mantenere la riservatezza e la sicurezza delle tue informazioni personali in ogni momento.",
      back: "Indietro",
      close: "✖"
    },
    contactPage: {
      title: "Contatto",
      description: "Puoi contattarci attraverso i seguenti mezzi:",
      email: "Email: contatto@piattaformaangelica.it",
      whatsapp: "WhatsApp: +123 456 789",
      instagram: "Instagram: @piattaforma_angelica",
      facebook: "Facebook: Piattaforma Angelica Ufficiale",
      thanks: "Grazie per averci contattato 🌟",
      responseMessage: "Ti risponderemo il prima possibile per aiutarti nel tuo percorso spirituale 🌟",
      back: "Indietro",
      close: "✖"
    },
    loadingMessages: [
      "Preparazione del tuo spazio sacro...",
      "Connessione con l'energia angelica...",
      "Apertura dei canali di luce divina...",
      "Invocazione della protezione celestiale...",
      "Attivazione della tua connessione spirituale...",
      "Gli angeli ti stanno aspettando...",
      "Creazione di un ambiente di pace e amore...",
      "Sintonizzazione con le frequenze angeliche...",
      "Preparazione del tuo incontro divino...",
      "Benvenuto nella tua trasformazione!"
    ],
    dashboard: {
      welcome: "Dashboard Personale",
      home: "Home",
      angelicReading: "Apertura Angelica",
      soundTherapy: "Sonoterapia e Canalizzazioni",
      therapies: "Terapie e Pulizie",
      academy: "Accademia Angelica",
      dailyMessage: "Messaggio Quotidiano",
      blogPodcast: "Blog & Podcast",
      store: "Negozio Angelico",
      level: "Livello",
      points: "Punti di Luce",
      consecutiveDays: "Giorni Consecutivi",
      completedSessions: "Sessioni",
      channelingsListened: "Canalizzazioni",
      coursesFinished: "Corsi",
      dailyMessageSection: "MESSAGGIO DEL GIORNO",
      seeAngelicMessages: "VEDI MESSAGGI ANGELICI",
      eventsTitle: "Prossimi Eventi dell'Angelologo",
      eventDate: "Data",
      eventTime: "Ora",
      eventDuration: "Durata",
      eventModality: "Modalità",
      eventLocation: "Luogo",
      eventPrice: "Prezzo",
      eventSpaces: "Posti",
      eventRegistered: "Iscritti",
      viewDetails: "Vedi Dettagli",
      subscribed: "Iscritto",
      subscribe: "Iscriviti",
      cart: "Carrello",
      emptyCart: "Il tuo carrello è vuoto",
      addProducts: "Aggiungi prodotti da qualsiasi sezione della piattaforma",
      total: "Totale",
      clearCart: "Svuota Carrello",
      proceedPayment: "Procedi al Pagamento",
      settings: "Impostazioni Utente",
      personalInfo: "Informazioni Personali",
      name: "Nome",
      lastName: "Cognome",
      email: "Email",
      phone: "Telefono",
      birthDate: "Data di Nascita",
      country: "Paese",
      platformPrefs: "Preferenze della Piattaforma",
      language: "Lingua",
      notifications: "Ricevere notifiche",
      emailMarketing: "Email promozionali",
      darkMode: "Modalità scura",
      saveChanges: "Salva Modifiche",
      logout: "Esci",
      events: {
        previous: "Precedente",
        next: "Successivo"
      }
    },
    calendar: {
      weekDays: ['Do', 'Lu', 'Ma', 'Me', 'Gi', 'Ve', 'Sa']
    }
  },
  'Português': {
    title: "PLATAFORMA ANGELICAL",
    blessing: "Deus nos abençoa mil vezes mil",
    subtitle: "Conecte-se com seus anjos.",
    subtitle2: "Transforme sua vida.",
    login: "🔒 Entrar",
    register: "👤 Cadastrar",
    language: "Idioma",
    followUs: "Siga-nos:",
    messageCount: "Mensagem",
    of: "de",
    loginPage: {
      title: "Entrar",
      subtitle: "Bem-vindo de volta à Plataforma Angelical",
      email: "Email",
      password: "Senha",
      loginButton: "Entrar",
      loading: "Carregando...",
      noAccount: "Não tem uma conta?",
      registerHere: "Cadastre-se aqui",
      forgotPassword: "Esqueceu sua senha?",
      back: "Voltar",
      invalidCredentials: "Credenciais inválidas. Tente novamente."
    },
    registerPage: {
      title: "Criar conta",
      subtitle: "Junte-se à nossa comunidade espiritual",
      firstName: "Nome",
      lastName: "Sobrenome",
      email: "Email",
      password: "Senha",
      confirmPassword: "Confirmar senha",
      preferredLanguage: "Idioma preferido",
      phone: "Telefone",
      address: "Endereço",
      city: "Cidade",
      state: "Estado / Província",
      postalCode: "Código postal",
      selectCountry: "Selecione um país",
      preferredContact: "Método de contato preferido",
      acceptTerms: "Eu aceito os",
      termsAndConditions: "Termos e condições",
      and: "e a",
      privacyPolicy: "Política de privacidade",
      registerButton: "Cadastrar",
      registering: "Cadastrando...",
      alreadyHaveAccount: "Já tem uma conta?",
      loginHere: "Faça login aqui",
      back: "Voltar",
      passwordMismatch: "As senhas não coincidem",
      success: "Cadastro realizado com sucesso. Verifique seu email para confirmar a conta.",
      ageError: "Você deve ter 18 anos ou mais para se cadastrar",
      personalInfo: "Informações Pessoais",
      security: "Segurança",
      preferences: "Preferências e Contato",
      location: "Localização",
      errorTitle: "Erro de Cadastro",
      understood: "Entendido",
      successTitle: "Cadastro Realizado com Sucesso!",
      goToLogin: "Ir para Login",
      ageErrorTitle: "Cadastro Não Permitido",
      ageErrorMessage: "Desculpe, o cadastro é restrito a pessoas maiores de 18 anos."
    },
    footer: {
      terms: "Termos de Uso",
      privacy: "Política de Privacidade",
      contact: "Contato",
      rightsReserved: "Todos os direitos reservados"
    },
    termsPage: {
      title: "Termos de Uso",
      description: "Bem-vindo à Plataforma Angelical. Ao acessar e usar nosso site, você concorda em cumprir os seguintes termos e condições:",
      point1: "O conteúdo oferecido é para fins espirituais e de bem-estar.",
      point2: "Não substitui tratamentos médicos ou terapêuticos profissionais.",
      point3: "O uso inadequado do conteúdo pode resultar na suspensão da conta.",
      point4: "Respeitamos a privacidade de seus dados de acordo com nossa política.",
      point5: "Reservamo-nos o direito de modificar estes termos a qualquer momento.",
      contentTitle: "Conteúdo Espiritual",
      useTitle: "Uso Responsável",
      policiesTitle: "Políticas de Uso",
      privacyTitle: "Privacidade",
      modificationsTitle: "Modificações",
      acceptance: "Aceitação dos Termos",
      acceptanceText: "Ao usar nossa plataforma, você confirma que leu, compreendeu e aceitou estes termos de uso.",
      back: "Voltar",
      close: "✖"
    },
    privacyPage: {
      title: "Política de Privacidade",
      description: "Na Plataforma Angelical, valorizamos profundamente sua privacidade e nos comprometemos a proteger suas informações pessoais. Esta política explica como coletamos, usamos e protegemos seus dados:",
      point1: "Os dados que você fornece (nome, email, preferências) são usados exclusivamente para oferecer uma experiência espiritual personalizada.",
      point2: "Não compartilhamos seus dados com terceiros sem seu consentimento expresso.",
      point3: "Usamos Supabase como backend seguro para armazenamento e autenticação de usuários.",
      point4: "Você pode solicitar a exclusão ou modificação de suas informações a qualquer momento.",
      point5: "Esta política pode ser atualizada para se adaptar a novas regulamentações ou melhorias do serviço.",
      dataTitle: "Uso de Dados Pessoais",
      protectionTitle: "Proteção de Informações",
      infrastructureTitle: "Infraestrutura Segura",
      rightsTitle: "Direitos do Usuário",
      updatesTitle: "Atualizações",
      commitment: "Nosso Compromisso",
      commitmentText: "Sua privacidade é fundamental para nós. Comprometemo-nos a manter a confidencialidade e segurança de suas informações pessoais o tempo todo.",
      back: "Voltar",
      close: "✖"
    },
    contactPage: {
      title: "Contato",
      description: "Você pode nos contatar através dos seguintes meios:",
      email: "Email: contato@plataformaangelical.com.br",
      whatsapp: "WhatsApp: +123 456 789",
      instagram: "Instagram: @plataforma_angelical",
      facebook: "Facebook: Plataforma Angelical Oficial",
      thanks: "Obrigado por entrar em contato conosco 🌟",
      responseMessage: "Responderemos o mais rápido possível para ajudá-lo em sua jornada espiritual 🌟",
      back: "Voltar",
      close: "✖"
    },
    loadingMessages: [
      "Preparando seu espaço sagrado...",
      "Conectando com a energia angelical...",
      "Abrindo os canais de luz divina...",
      "Invocando a proteção celestial...",
      "Ativando sua conexão espiritual...",
      "Os anjos estão esperando por você...",
      "Criando um ambiente de paz e amor...",
      "Sintonizando com as frequências angelicais...",
      "Preparando seu encontro divino...",
      "Bem-vindo à sua transformação!"
    ],
    dashboard: {
      welcome: "Painel Pessoal",
      home: "Início",
      angelicReading: "Abertura Angelical",
      soundTherapy: "Sonoterapia e Canalizações",
      therapies: "Terapias e Limpezas",
      academy: "Academia Angelical",
      dailyMessage: "Mensagem Diária",
      blogPodcast: "Blog & Podcast",
      store: "Loja Angelical",
      level: "Nível",
      points: "Pontos de Luz",
      consecutiveDays: "Dias Consecutivos",
      completedSessions: "Sessões",
      channelingsListened: "Canalizações",
      coursesFinished: "Cursos",
      dailyMessageSection: "MENSAGEM DO DIA",
      seeAngelicMessages: "VER MENSAGENS ANGELICAIS",
      eventsTitle: "Próximos Eventos do Angelólogo",
      eventDate: "Data",
      eventTime: "Hora",
      eventDuration: "Duração",
      eventModality: "Modalidade",
      eventLocation: "Localização",
      eventPrice: "Preço",
      eventSpaces: "Vagas",
      eventRegistered: "Inscritos",
      viewDetails: "Ver Detalhes",
      subscribed: "Inscrito",
      subscribe: "Inscrever-se",
      cart: "Carrinho de Compras",
      emptyCart: "Seu carrinho está vazio",
      addProducts: "Adicione produtos de qualquer seção da plataforma",
      total: "Total",
      clearCart: "Limpar Carrinho",
      proceedPayment: "Prosseguir para o Pagamento",
      settings: "Configurações do Usuário",
      personalInfo: "Informações Pessoais",
      name: "Nome",
      lastName: "Sobrenome",
      email: "Email",
      phone: "Telefone",
      birthDate: "Data de Nascimento",
      country: "País",
      platformPrefs: "Preferências da Plataforma",
      language: "Idioma",
      notifications: "Receber notificações",
      emailMarketing: "Emails promocionais",
      darkMode: "Modo escuro",
      saveChanges: "Salvar Alterações",
      logout: "Sair",
      events: {
        previous: "Anterior",
        next: "Próximo"
      }
    },
    calendar: {
      weekDays: ['Do', 'Se', 'Te', 'Qu', 'Qu', 'Se', 'Sá']
    }
  }
};

// Provider del contexto
export const LanguageProvider = ({ children }) => {
  const [selectedLanguage, setSelectedLanguage] = useState('Español');

  const changeLanguage = (language) => {
    console.log(`🌍 Cambiando idioma globalmente a: ${language}`);
    setSelectedLanguage(language);
  };

  const getCurrentTranslation = () => {
    return TRANSLATIONS[selectedLanguage];
  };

  const value = {
    selectedLanguage,
    changeLanguage,
    getCurrentTranslation,
    availableLanguages: AVAILABLE_LANGUAGES,
    translations: TRANSLATIONS
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personalizado para usar el contexto
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe ser usado dentro de un LanguageProvider');
  }
  
  // Crear alias 't' para getCurrentTranslation()
  return {
    ...context,
    t: context.getCurrentTranslation()
  };
};

export default LanguageContext;