// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kolciyzkuvcwzegsomww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbGNpeXprdXZjd3plZ3NvbXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODY0NTAsImV4cCI6MjA2NjM2MjQ1MH0.n6HbwCXo3lGW9gBSAUAbOufZf9UBmEvkeEX891dnswg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});